### ISSUE TITLE
sort.py

### ISSUE THREAD

**Issue by SadPersonn** [RunaCapital/awesome-oss-alternatives#59]
Traceback (most recent call last):
  File "/disc1/programming/awesome-oss-alternatives/sort.py", line 25, in <module>
    sort_readme()
  File "/disc1/programming/awesome-oss-alternatives/sort.py", line 12, in sort_readme
    pairs = [(find_cat(x), find_name(x)) for x in all[idx + 2: -1]]
  File "/disc1/programming/awesome-oss-alternatives/sort.py", line 12, in <listcomp>
    pairs = [(find_cat(x), find_name(x)) for x in all[idx + 2: -1]]
  File "/disc1/programming/awesome-oss-alternatives/sort.py", line 10, in <lambda>
    find_cat = lambda x: x[:x.index('|')].strip()
ValueError: substring not found

**Comment by garrrikkotua** [comment]
It is actually solved, so closing :)
